name: "Bug report"
description: "Create a report to help us improve"
labels:
  - "bug"
title: "Bug report:"
body:

  - type: input
    attributes:
      label: "Describe the bug"
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. ...
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: "Additional context and screenshots if applicable"
    validations:
      required: false