name: "Feature request"
description: Suggest an idea for this project
labels:
  - enhancement
title: "Feature request:"
body:

  - type: textarea
    attributes:
      label: Problem
      description: Is your feature request related to a specific problem? If not, please describe the general idea of your request.
      placeholder: "e.g. I want to mute notifications for set period of time"
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
      description: A clear and concise description of what you want to happen.
      placeholder: "e.g. Add 'Mute notifications for' button that asks when to enable notifications"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "e.g. Mute and unmute notification manually"
    validations:
      required: false