@TaSked_HostAddress = http://localhost:5070
@User_Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjQ4ZGU2My04NWExLTQ2ZWItOGE1Mi05YjVmOGMzMzJlZTQiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDcwLyIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwNzAvIn0.C0BmFBh2yKCnlVuGG8NdvI8G5v7ZxvRAw_SzFNS0R3A
@Subject_Id = f0697c21-fe93-4b69-b5df-3d0c2fdb439b

POST {{TaSked_HostAddress}}/user/anonymousAccout
Content-Type: application/json
Accept: application/json

{
    "Nickname": "TestUser"
}
###

POST {{TaSked_HostAddress}}/Group
Content-Type: application/json
Accept: application/json
Authorization: bearer {{User_Token}}

"Test Group"
###

POST {{TaSked_HostAddress}}/subject
Content-Type: application/json
Authorization: bearer {{User_Token}}

"Test subject"
###


GET {{TaSked_HostAddress}}/homework
Content-Type: application/json
Accept: application/json
Authorization: bearer {{User_Token}}


###

POST {{TaSked_HostAddress}}/homework
Content-Type: application/json
Authorization: bearer {{User_Token}}

{
    "UserId": "{{Subject_Id}}",
    "SubjectId": "{{Subject_Id}}",
    "Title": "Test task",
    "Description": "Test task"
}

###
