//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaSked.App.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaSked.App.Resources.Localization.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateGroup_Form_ConfirmButton {
            get {
                return ResourceManager.GetString("CreateGroup.Form.ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string CreateGroup_Form_GroupName {
            get {
                return ResourceManager.GetString("CreateGroup.Form.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You nickname would be visible to moderators only. It could not be changed..
        /// </summary>
        internal static string CreateGroup_Form_Hint {
            get {
                return ResourceManager.GetString("CreateGroup.Form.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string CreateGroup_Form_Nickname {
            get {
                return ResourceManager.GetString("CreateGroup.Form.Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group.
        /// </summary>
        internal static string CreateGroup_Form_Title {
            get {
                return ResourceManager.GetString("CreateGroup.Form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy invitation Id.
        /// </summary>
        internal static string Invitation_Card_CopyId {
            get {
                return ResourceManager.GetString("Invitation.Card.CopyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string JoinGroup_Form_ConfirmButton {
            get {
                return ResourceManager.GetString("JoinGroup.Form.ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You nickname would be visible to moderators only. It could not be changed..
        /// </summary>
        internal static string JoinGroup_Form_Hint {
            get {
                return ResourceManager.GetString("JoinGroup.Form.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Id.
        /// </summary>
        internal static string JoinGroup_Form_InvitationId {
            get {
                return ResourceManager.GetString("JoinGroup.Form.InvitationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string JoinGroup_Form_Nickname {
            get {
                return ResourceManager.GetString("JoinGroup.Form.Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join group.
        /// </summary>
        internal static string JoinGroup_Form_Title {
            get {
                return ResourceManager.GetString("JoinGroup.Form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Language_Default {
            get {
                return ResourceManager.GetString("Language.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string Language_Ukrainian {
            get {
                return ResourceManager.GetString("Language.Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        internal static string Loading_Authenticating {
            get {
                return ResourceManager.GetString("Loading.Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing request....
        /// </summary>
        internal static string LoadingIndicator_Processing {
            get {
                return ResourceManager.GetString("LoadingIndicator.Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group.
        /// </summary>
        internal static string Main_CreateGroup {
            get {
                return ResourceManager.GetString("Main.CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group as an admin.
        /// </summary>
        internal static string Main_CreateGroupCaption {
            get {
                return ResourceManager.GetString("Main.CreateGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join group.
        /// </summary>
        internal static string Main_JoinGroup {
            get {
                return ResourceManager.GetString("Main.JoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join existing group by invitation.
        /// </summary>
        internal static string Main_JoinGroupCaption {
            get {
                return ResourceManager.GetString("Main.JoinGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaSked - shared place for homework.
        /// </summary>
        internal static string Main_Slogan {
            get {
                return ResourceManager.GetString("Main.Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group.
        /// </summary>
        internal static string Navigation_Groups_Create {
            get {
                return ResourceManager.GetString("Navigation.Groups.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join group.
        /// </summary>
        internal static string Navigation_Groups_Join {
            get {
                return ResourceManager.GetString("Navigation.Groups.Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Navigation_Loading {
            get {
                return ResourceManager.GetString("Navigation.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaSked.
        /// </summary>
        internal static string Navigation_Main {
            get {
                return ResourceManager.GetString("Navigation.Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Navigation_Reports {
            get {
                return ResourceManager.GetString("Navigation.Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create report.
        /// </summary>
        internal static string Navigation_Reports_Create {
            get {
                return ResourceManager.GetString("Navigation.Reports.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Navigation_Settings {
            get {
                return ResourceManager.GetString("Navigation.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations.
        /// </summary>
        internal static string Navigation_Settings_Invitations {
            get {
                return ResourceManager.GetString("Navigation.Settings.Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Navigation_Settings_Roles {
            get {
                return ResourceManager.GetString("Navigation.Settings.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        internal static string Navigation_Subjects {
            get {
                return ResourceManager.GetString("Navigation.Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Navigation_Tasks {
            get {
                return ResourceManager.GetString("Navigation.Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Navigation_Tasks_All {
            get {
                return ResourceManager.GetString("Navigation.Tasks.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By subjects.
        /// </summary>
        internal static string Navigation_Tasks_BySubjects {
            get {
                return ResourceManager.GetString("Navigation.Tasks.BySubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create task.
        /// </summary>
        internal static string Navigation_Tasks_Create {
            get {
                return ResourceManager.GetString("Navigation.Tasks.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompleted.
        /// </summary>
        internal static string Navigation_Tasks_Uncompleted {
            get {
                return ResourceManager.GetString("Navigation.Tasks.Uncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Report_Form_Create {
            get {
                return ResourceManager.GetString("Report.Form.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports can`t be changed or deleted.
        /// </summary>
        internal static string Report_Form_Hint {
            get {
                return ResourceManager.GetString("Report.Form.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Report_Form_Message {
            get {
                return ResourceManager.GetString("Report.Form.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create report.
        /// </summary>
        internal static string Report_Form_Title {
            get {
                return ResourceManager.GetString("Report.Form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        internal static string Role_Card_Ban {
            get {
                return ResourceManager.GetString("Role.Card.Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote.
        /// </summary>
        internal static string Role_Card_Promote {
            get {
                return ResourceManager.GetString("Role.Card.Promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Settings_Group_Account {
            get {
                return ResourceManager.GetString("Settings.Group.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Settings_Group_Group {
            get {
                return ResourceManager.GetString("Settings.Group.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Group_Language {
            get {
                return ResourceManager.GetString("Settings.Group.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage invitations.
        /// </summary>
        internal static string Settings_Invitations {
            get {
                return ResourceManager.GetString("Settings.Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Settings_Logout {
            get {
                return ResourceManager.GetString("Settings.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage members.
        /// </summary>
        internal static string Settings_Roles {
            get {
                return ResourceManager.GetString("Settings.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Subject_Action_Delete {
            get {
                return ResourceManager.GetString("Subject.Action.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Subject_Action_Update {
            get {
                return ResourceManager.GetString("Subject.Action.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Subject_Form_Create {
            get {
                return ResourceManager.GetString("Subject.Form.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Subject.
        /// </summary>
        internal static string Subject_Form_Create_Title {
            get {
                return ResourceManager.GetString("Subject.Form.Create.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher name.
        /// </summary>
        internal static string Subject_Form_TeacherName {
            get {
                return ResourceManager.GetString("Subject.Form.TeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Subject_Form_Title {
            get {
                return ResourceManager.GetString("Subject.Form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Subject_Form_Update {
            get {
                return ResourceManager.GetString("Subject.Form.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subject.
        /// </summary>
        internal static string Subject_Form_Update_Title {
            get {
                return ResourceManager.GetString("Subject.Form.Update.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color.
        /// </summary>
        internal static string Task_Action_ChangeColor {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Task_Action_ChangeColor_Cancel {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Task_Action_ChangeColor_Color_Green {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor.Color.Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Task_Action_ChangeColor_Color_Orange {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor.Color.Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Task_Action_ChangeColor_Color_Purple {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor.Color.Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Task_Action_ChangeColor_Color_Red {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor.Color.Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string Task_Action_ChangeColor_Color_White {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor.Color.White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yelllow.
        /// </summary>
        internal static string Task_Action_ChangeColor_Color_Yellow {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor.Color.Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose task color.
        /// </summary>
        internal static string Task_Action_ChangeColor_Title {
            get {
                return ResourceManager.GetString("Task.Action.ChangeColor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Task_Action_Complete {
            get {
                return ResourceManager.GetString("Task.Action.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Task_Action_Delete {
            get {
                return ResourceManager.GetString("Task.Action.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark uncompleted.
        /// </summary>
        internal static string Task_Action_Uncomplete {
            get {
                return ResourceManager.GetString("Task.Action.Uncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Task_Action_Update {
            get {
                return ResourceManager.GetString("Task.Action.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Task_Form_Create {
            get {
                return ResourceManager.GetString("Task.Form.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create homework.
        /// </summary>
        internal static string Task_Form_Create_Title {
            get {
                return ResourceManager.GetString("Task.Form.Create.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string Task_Form_Deadline {
            get {
                return ResourceManager.GetString("Task.Form.Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Task_Form_Description {
            get {
                return ResourceManager.GetString("Task.Form.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Task_Form_Subject {
            get {
                return ResourceManager.GetString("Task.Form.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Task_Form_Title {
            get {
                return ResourceManager.GetString("Task.Form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Task_Form_Update {
            get {
                return ResourceManager.GetString("Task.Form.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update homework.
        /// </summary>
        internal static string Task_Form_Update_Title {
            get {
                return ResourceManager.GetString("Task.Form.Update.Title", resourceCulture);
            }
        }
    }
}
